# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3
fail_fast: true
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.0.1
        hooks:
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-ast
        -   id: check-builtin-literals
        -   id: check-case-conflict
        -   id: check-merge-conflict
        -   id: check-toml
        -   id: debug-statements
        -   id: forbid-new-submodules
    -   repo: local
        hooks:
        -   id: export-requirements
            name: Convert pyproject.toml to requirements.txt
            description: Generate requirements.txt pyproject.toml for backwards compatibility.
            language: system
            entry: poetry export -f requirements.txt -o requirements.txt --without-hashes
            files: "^pyproject.toml$"
            pass_filenames: false
    -   repo: https://github.com/sirosen/check-jsonschema
        rev: 0.6.0
        hooks:
        -   id: check-github-workflows
        -   id: check-github-actions
    -   repo: https://github.com/psf/black
        rev: 21.10b0
        hooks:
        -   id: black
    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.29.0
        hooks:
        -   id: pyupgrade
    -   repo: https://github.com/PyCQA/flake8
        rev: 4.0.1
        hooks:
        -   id: flake8
    -   repo: https://github.com/DavidAnson/markdownlint-cli2
        rev: v0.3.2
        hooks:
        -   id: markdownlint-cli2


