version: 2.1

orbs:
  python: circleci/python@1.5
  codecov: codecov/codecov@3.2.2

jobs:
  test-and-cover:
    executor: 
      name: python/default
      tag: 3.9.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run coverage run -m pytest
            poetry run coverage xml
          name: Test/cover it
      - codecov/upload:
          file: ./coverage.xml

workflows:
  workflow:
    jobs:
      - test-and-cover
