version: 2.1

orbs:
  python: circleci/python@1.5

jobs:
  build-and-test:
    executor: 
      name: python/default
      tag: 3.9.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry run pytest --version
          name: Test it
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

workflows:
  workflow:
    jobs:
      - build-and-test
