version: 2.1

orbs:
  python: circleci/python@1.5
  codecov: codecov/codecov@3.2

jobs:
  upload:
    docker:
      - image: cimg/base:stable
    steps:
      - codecov/upload:
          file: ./coverage.xml 

workflows:
  workflow:
    jobs:
      - python/test:
          test-tool: pytest 
          test-tool-args: --cov-report=xml 
          pkg-manager: poetry
      - upload:
          requires:
            - python/test
